---
######################## The below task will be run on Linux Hosts and Fetch the report ######################

- name: Capture timestamp in uptime role
  shell: date +"%Y%m%d%H%M%S"
  register: current_date_time

- name: Gather last reboot
  ansible.builtin.shell: who -b |awk '{print $3}'
  register: rebooted
  become: yes

- name: Check Uptime in uptime role
  shell: uptime | cut -d ',' -f1 | awk '{print $3, $4}'
  register: uptime
  become: yes

- name: Get latest patch details 
  shell: "{{ linux_commands[ ansible_facts['os_family']|lower + '_command' ] }}"
  register: patch_details
  become: yes

- name: Build out CSV content
  set_fact:
    dev_info: "{{ ansible_fqdn }},{{ ansible_default_ipv4.address }},{{ ansible_distribution }},{{ ansible_kernel }},{{ rebooted.stdout }},{{ uptime.stdout }},{{ patch_details.stdout }}"
  become: yes

################# The below two task will be run in localhost  #################

- name: Generate CSV file
  template: 
    src: templates/uptime.txt.j2 
    dest: "{{ csv_path }}/{{ csv_filename }}"
  delegate_to: localhost
  
- name: Send Email
  mail:
    host: "{{ email_host }}"
    from: "{{ email_from }}"
    port: 25
    to: "{{ email_to }}"
    subject: "[Ansible] *{{ email_subject }}*"
    body: "{{ lookup('template', 'templates/report.html.j2', errors='ignore') }}"
    attach: "{{ csv_path }}/{{ csv_filename }}"
    subtype: html
  run_once: true
  delegate_to: localhost
...

